#!/bin/sh 

cd ${0%/*} || exit 1 #Run from this directory

if [ ! -d constant/polyMesh ]
then
    runApplication blockMesh
    runApplication checkMesh -allTopology -allGeometry -constant
fi
pisoFoamspecdpdxi > log

#plot residuals
#gnuplot plotResiduals -
