#!/bin/sh 

cd ${0%/*} || exit 1 #Run from this directory

#Clean time directories only
rm -rf *[1-9]* 
rm -r *.log processor*

if [ -d "postProcessing/sample/" ]; then
	cd postProcessing/sample/
	rm -rf *[1-9]*
	cd ../
	rm -rf wallShearStress yPlus residuals
fi
