#!/bin/bash

foamLog log >/dev/null

gnuplot -persist > /dev/null 2>&1 << EOF
        set logscale y
        set title "Residuals vs iteration"
        set xlabel "Iteration"
        set ylabel "Residuals"
        plot "logs/Ux_0" with lines,\
             "logs/Uy_0" with lines,\
             "logs/Uz_0" with lines,\
             "logs/p_0" with lines,\
             "logs/k_0" with lines,\
             "logs/epsilon_0" with lines
EOF

# ----------------------------------------------------------------- end-of-file
