#!/bin/sh 

cd ${0%/*} || exit 1 #Run from this directory

#Clean time directories only
rm -rf *[1-9]* 
rm -r log

if [ -d "postProcessing/sample/" ]; then
	cd postProcessing/sample/
	rm -rf *[1-9]*
	cd ../
	rm -rf wallShearStress
	rm -rf yPlus
	rm -rf residuals
fi
