#!/bin/sh 

cd ${0%/*} || exit 1 #Run from this directory

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! -d constant/polyMesh ]
then
    blockMesh
    checkMesh -allTopology -allGeometry -constant
fi
pimpleFoam > log

postChannel
#plot residuals
#./plotresiduals

postProcess -func "components(U)" -latestTime
postProcess -func sample -latestTime
#echo $!
#python3 Uplus_Tplus_k_uv_KEPS.py postProcess/sample/$latestTime/vertical

