#!/bin/sh 

cd ${0%/*} || exit 1 #Run from this directory

if [ ! -d constant/polyMesh ]
then
    runApplication blockMesh
    runApplication checkMesh -allTopology -allGeometry -constant
fi
 pimpleFoam> log

#plot residuals
#gnuplot plotResiduals 

postProcess -func "components(U)" -latestTime
postProcess -func sample -latestTime
echo $!
#python3 Uplus_Tplus_k_uv_KEPS.py postProcess/sample/$latestTime/vertical

